# pipeline_connect.py
import subprocess
import importlib.util
import sys
import test
import os


import os
os.chdir(os.path.dirname(__file__))  # switch to qna_system folder


# Step 1: Run test.py and get student answer
print("📤 Getting student's written answer from test.py ...")
import sys
subprocess.run([sys.executable, "test.py"], check=True)



# test.py saves recognized text in recognized_text.txt
if not os.path.exists("recognized_text.txt"):
    print("❌ No recognized_text.txt found! Ensure test.py writes output to file.")
    sys.exit(1)

with open("recognized_text.txt", "r", encoding="utf-8") as f:
    student_answer = f.read().strip()

print("\n🧾 Student Answer Loaded Successfully!\n")

# Step 2: Get reference answer (already generated by your QnA system)
if not os.path.exists("reference_answer.txt"):
    print("❌ reference_answer.txt not found! Please save QnA output there.")
    sys.exit(1)

with open("reference_answer.txt", "r", encoding="utf-8") as f:
    reference_answer = f.read().strip()

print("\n📚 Reference Answer Loaded Successfully!\n")

# Step 3: Call evaluate_answer.py to compute similarity
print("⚖️  Evaluating student's answer...\n")

# Import evaluate_answer dynamically and call the function
spec = importlib.util.spec_from_file_location("evaluate_answer", "evaluate_answer.py")
evaluate_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(evaluate_module)

evaluate_module.evaluate_answer(reference_answer, student_answer)

print("\n🏁 Evaluation Complete.")
